data:
  project_root: 
  project_path: "."

  train_image_root: "./new_train/btd_image/arm"
  train_label_root: "./new_train/label/arm"

  valid_image_root: "./new_valid/btd_image/arm"
  valid_label_root: "./new_valid/label/arm"
  valid_output_root: "./output"

  test_image_root: "./new_test/image"
  test_result_root: "./result"

  target_class: "arm"
  size: 1024

wandb:
  project: "arm segmentation"
  notes: "Unet + Eff-b3 with btd image"
  name: "Unet + Eff-b3 with btd image"
  tags:

checkpoint:
  dir: "checkpoints"
  model_name: 'best_arm_model.pt'

model:
  name: "Unet"                  # SMP 라이브러리에서 불러올 모델
  encoder: "efficientnet-b3"    # 인코더 설정
  pretrained: "imagenet"        # 기 학습 가중치 설정
  in_channels: 3                # 입력 이미지 채널 수
  classes: 1                    # 분류 클래스 수

train:
  epoch: 31                     # 학습 에포크 설정
  batch_size: 8                 # 학습 배치 설정
  num_workers: 6                # 데이터로더 워커 설정
  mixed_precision: true         # 학습 속도, 메모리 최적화 옵션
  gradient_accum: 1             # 유효 배치 배수 (배치놈에는 소용 없음)

valid:
  epoch: 1                      # 검증 수행 주기
  batch_size: 4                 # 검증 배치 설정
  num_workers: 4                # 데이터로더 워커 설정
  threshold: 0.5                # 클래스 식별 기준치 설정

test:
  batch_size: 4                 # 검증 배치 설정
  num_workers: 4                # 데이터로더 워커 설정
  threshold: 0.5                # 클래스 식별 기준치 설정
  output_csv: "output.csv"      # 

augmentation:
  train:
    resize: false               
    normalize: true             # 정규화 (imagenet 기준)
    horizontal_flip: 0.5          # 좌우 반전 (기본: 0.5)
    scale: 0.1                    # 이미지 가로 세로 수축 (기본: 0.2)
    shift: 0.05                    # 상하좌우 이동 (기본: 0.1)
    rotate: 0                   # 회전 (기본 15)
    shear: 0                    # 기울이기 (기본: 0.1)
    crop: 0                 # 부분 포착
    elastic: 0                 # 부분 포착
  valid:
    resize: false               # 이미지 해상도 조절
    normalize: true             # 정규화 (imagenet 기준)

optimizer:
  name: "adamW"                 # 최적자 설정
  learning_rate:                # 학습률 설정
      encoder: 4e-4               # 인코더 학습률
      decoder: 4e-4               # 디코더 학습률
      head: 4e-4                  # 분류 헤드 학습률
  weight_decay: 1e-5            # 가중최 감쇠

scheduler:
  warmup_epoch: 1               # 웜업 기간
  linear: true                  # warmup에 사용할 LinearLR 스케줄러

  cosine_period: 3              # cosine_restart 스케줄러 반복 주기
  cosine_restart: true          # warmup 이후 사용할 CosineAnnealingWarmRestarts 스케줄러
  cosine_anneal: false          

loss:
  bce: 0                        # loss 내 bce 손실 가중 계수 설정
  dice: 1                       # loss 내 dice 손실 가중 계수 설정
  tversky: 0                    # loss 내 tversky 손실 가중 계수 설정
  log_dice: 0                   # loss 내 log_dice 손실 가중 계수 설정
  focal_dice: 0                 # loss 내 focal dice 손실 가중 계수 설정 (tversky로 구현)
  focal_bce: 0                  # loss 내 focal bce 손실 가중 계수 설정
  smooth_bce: 0                 # loss 내 smooth bce 손실 가중 계수 설정
  edge_bce: 0                   # loss 내 edge-weighted bce 손실 가중 계수 설정
  sobel_edge: 0                 # loss 내 sobel edge 손실 가중 계수 설정

  class_weight_dice: 0          # loss 내 class_weight_dice 손실 가중 계수 설정
  class_weight_bce: 0           # loss 내 bce 손실 가중 계수 설정

  class_focal_dice: 0         # class_weight_dice + focal    
  class_focal_bce: 0          # class_weight_bce + focal

  class_focal_tverksy: 0        # class_focal_dice + FN/FP 조절

performance:
  dice: true

other:
  seed: 21

classes:
  - 'Radius'
  - 'Ulna'